### ISSUE TITLE
Cannot enable ID3 editor on Nextcloud 18. Requires PHP 7.3 or lower.

### ISSUE THREAD

**Issue by ShapeShifter499** [Rello/audioplayer_editor#2]
Cannot enable ID3 editor on Nextcloud 18. Requires PHP 7.3 or lower. I get the below message in Nextcloud.

```
This app cannot be installed because the following dependencies are not fulfilled:

    PHP with a version lower than 7.3 is required. 
```

**Comment by Rello** [comment]
Thank you for the hint. 
I missed that one
Will do

**Comment by neofutur** [comment]
+1 I need this but cant downgrade php. please update !

**Comment by Rello** [comment]
Hey,
sorry for the delay. I was caught up with the Analytics app.
I just released v 0.2.1.
Please let me know if you encounter issues, as I don´t have  a running 7.4

**Comment by ShapeShifter499** [comment]
I have this issue still.  I updated to version 0.2.2  today and I still have the issue.
```
This app cannot be installed because the following dependencies are not fulfilled:

    PHP with a version lower than 7.3 is required. 
```
![Screenshot_2020-04-15_18-43-29](https://user-images.githubusercontent.com/388665/79405521-82155e00-7f49-11ea-8cee-e6430a4bd20a.png)

**Comment by ShapeShifter499** [comment]
Update, it works but I had to disable and uninstall before installing the latest version again to make it work.
